name: C++ CI

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: false
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

env:
  BUILD_TYPE: ${{ inputs.build_type || 'Debug' }}
  EXECUTABLE_NAME: "oop"
  INPUT_FILENAME: "tastatura.txt"
  BIN_DIR: "bin"
  BUILD_DIR: "build"

jobs:
  cppcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: |
          sudo apt update
          sudo apt install -y cppcheck

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c++20 --quiet src/ generated/src/

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        compiler: [gcc, clang, msvc]
        build_type: [Debug, Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash  # Ensure bash is used on all platforms
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            sudo apt update
            sudo apt install -y libopencv-dev libsfml-dev cmake g++ libudev-dev
          elif [ "${{ matrix.os }}" == "macos-14" ]; then
            if ! command -v brew &> /dev/null; then
              echo "Homebrew not found. Installing..."
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            fi
            brew install opencv sfml cmake llvm
          elif [ "${{ matrix.os }}" == "windows-2022" ]; then
            # Install OpenCV via Chocolatey
            choco install opencv --yes --limit-output
            if [ $? -eq 0 ]; then
              echo "OpenCV installed successfully."
            else
              echo "OpenCV installation failed." >&2
              exit 1
            fi

            # Try installing SFML using Chocolatey or fallback to manual installation
            choco install sfml --yes --limit-output || {
              echo "SFML package not found in Chocolatey. Attempting manual installation."
              # Download SFML from the official website
              curl -L https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip -o C:/tools/sfml.zip
              if [ $? -eq 0 ]; then
                echo "SFML downloaded successfully."
              else
                echo "Error downloading SFML." >&2
                exit 1
              fi

              # Unzip SFML to C:/tools/sfml
              unzip C:/tools/sfml.zip -d C:/tools/sfml
              if [ $? -eq 0 ]; then
                echo "SFML extracted successfully."
              else
                echo "Error extracting SFML." >&2
                exit 1
              fi

              # Verify that SFML was extracted
              if [ ! -d "C:/tools/sfml/SFML-2.5.1" ]; then
                echo "Error: SFML directory not found at C:/tools/sfml/SFML-2.5.1" >&2
                exit 1
              fi
            }

            # Set environment variables using PowerShell
            pwsh -Command "[System.Environment]::SetEnvironmentVariable('OpenCV_DIR', 'C:/tools/opencv/build', 'User')"
            pwsh -Command "[System.Environment]::SetEnvironmentVariable('SFML_DIR', 'C:/tools/sfml/SFML-2.5.1', 'User')"
            echo "OpenCV and SFML environment variables set."

            # Configuring OpenCV_DIR and SFML_DIR for GitHub environment
            echo "Configuring OpenCV_DIR"
            echo "C:/tools/opencv/build" >> $env:GITHUB_ENV
            echo "Configuring SFML_DIR"
            echo "C:/tools/sfml/SFML-2.5.1" >> $env:GITHUB_ENV
          fi

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-tidy
        run: |
          sudo apt update
          sudo apt install -y clang-tidy

      - name: Run clang-tidy
        run: |
          # Ensure that there are .cpp files in the src directory and its subdirectories
          CPP_FILES=$(find src -name "*.cpp")
          if [ -n "$CPP_FILES" ]; then
            clang-tidy $CPP_FILES -- -std=c++20
          else
            echo "No .cpp files found in the 'src' directory."
          fi
